name: Notify Discord on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | jq -sRr @uri)
        ISSUE_BODY=$(echo "${{ github.event.issue.body }}" | jq -sRr @uri)
        ISSUE_URL=${{ github.event.issue.html_url }}
        
        PAYLOAD='{"content":"**New Issue Created**\n\nTitle: '${ISSUE_TITLE}'\n\nDescription: '${ISSUE_BODY}'\n\nURL: '${ISSUE_URL}'"}'
        
        curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "${PAYLOAD}" "${DISCORD_WEBHOOK_URL}"